export const Products = [
  {
    id: 1,
    title: 'iPhone 15 Pro',
    brand: 'Apple',
    imageUrl: 'https://www.apple.com/v/iphone/compare/ag/images/overview/compare_iphone15_pro_blue_titanium__qh0ufmknzyi6_large_2x.jpg',
    description: 'O design inovador tem vidro inteiramente colorido por infusão na parte de trás. O processo personalizado de troca iônica dupla aplicado no vidro e a estrutura de alumínio aerospacial contribuem para deixar o iPhone 15 ainda mais durável.',
    price: 9299, 
  },
  {
    id: 2,
    title: 'iPhone 15',
    brand: 'Apple',
    imageUrl: 'https://www.apple.com/v/iphone/compare/ag/images/overview/compare_iphone15_blue__f9xmqcw1fsia_large_2x.jpg',
    description: 'O design inovador tem vidro inteiramente colorido por infusão na parte de trás. O processo personalizado de troca iônica dupla aplicado no vidro e a estrutura de alumínio aerospacial contribuem para deixar o iPhone 15 ainda mais durável.',
    price: 7299, 
  },
  {
    id: 3,
    title: 'iPhone 14',
    brand: 'Apple',
    imageUrl: 'https://www.apple.com/v/iphone/compare/ag/images/overview/compare_iphone14_purple__e92m8vvthziq_large_2x.jpg',
    description: 'O design inovador tem vidro inteiramente colorido por infusão na parte de trás. O processo personalizado de troca iônica dupla aplicado no vidro e a estrutura de alumínio aerospacial contribuem para deixar o iPhone 15 ainda mais durável.',
    price: 5999, 
  },
  {
    id: 4,
    title: 'iPhone 13',
    brand: 'Apple',
    imageUrl: 'https://www.apple.com/v/iphone/compare/ag/images/overview/compare_iphone13_blue__ca74x83zbcpe_large_2x.jpg',
    description: 'O design inovador tem vidro inteiramente colorido por infusão na parte de trás. O processo personalizado de troca iônica dupla aplicado no vidro e a estrutura de alumínio aerospacial contribuem para deixar o iPhone 15 ainda mais durável.',
    price: 5299, 
  },
  {
    id: 5,
    title: 'iPhone SE',
    brand: 'Apple',
    imageUrl: 'https://www.apple.com/v/iphone/compare/ag/images/overview/compare_iphoneSE_3rd_gen_starlight__bvj733gg7hde_large_2x.jpg',
    description: 'O design inovador tem vidro inteiramente colorido por infusão na parte de trás. O processo personalizado de troca iônica dupla aplicado no vidro e a estrutura de alumínio aerospacial contribuem para deixar o iPhone 15 ainda mais durável.',
    price: 4299, 
  },
]